apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-test-app
  labels:
    app: flink-test-app
  annotations:
    kubernetes.io/change-cause: deployment $IMAGE
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: flink-test-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flink-test-app
    spec:
      containers:
      - env:
        - name: MARIADB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: mariadb-password
        - name: SPRING_PROFILES_ACTIVE
          value: prod

        name: flink-test-app
        image: $IMAGE
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"

